[theme]
base = "light"
primaryColor = "#25317e"
backgroundColor = "#f3f7fb"
secondaryBackgroundColor = "#eef3fc"
textColor = "#1a2340"
font = "sans serif"

[client]
toolbarMode = "minimal"   # optional

[server]
runOnSave = true          # optional
